bundler_args: --without masochism benchmark
rvm:
  - 1.9.2
  - 1.9.3
  - 2.0.0
  - 2.1.0
  - 2.2.6
  - 2.3.2
  - jruby-9.1.6.0
  - jruby-19mode
  - rbx-19mode
  - ruby-head
  - jruby-head
matrix:
  allow_failures:
    - rvm: ruby-head
